highlighter:      pygments
# permalink
permalink: /:title/

# Setup
title: Comics

keywords: [comics]

url: http://comics.daozhang.info
baseurl: /
encoding: utf-8

author:
    name: 'Chris Qiu'
    url: http://daozhang.info
    email: 'qwh005007@gmail.com'

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
        - "/feed.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
